apiVersion: v1
kind: Service
metadata:
  name: calculator-stg-service
spec:
  selector:
    app: calculator-stg
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
