apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: calculator-stg
  name: calculator-stg-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-stg
  template:
    metadata:
      labels:
        app: calculator-stg
    spec:
      containers:
        - image: cx-harbor.btech.id/calc/test-app:v1.0.9-rc
          name: calculator-stg-container
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
