# file name: create-image.yml
name: ci-cd-github-argo
on:
  push:
    tags:
      - 'v*'

jobs:
  build-image:
    name: Checkout & Build Image
    runs-on: self-hosted
    steps:
      - name: Get Version
        id: get-version
        run: |
          echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Image
        run: |
          echo ${{ secrets.HARBOR_PASSWORD }} | docker login ${{ secrets.HARBOR_URL }} -u ${{ secrets.HARBOR_USERNAME }} --password-stdin
          cd app
          docker build -t test-app:${{ steps.get-version.outputs.VERSION }}-rc .
          echo 'Created Image with name:tag = test-app:${{ steps.get-version.outputs.VERSION }}-rc'

      - name: get-images-id
        id: image-id
        run: |
          echo ::set-output name=IMAGE_ID::$(docker images -q test-app:${{ steps.get-version.outputs.VERSION }}-rc)

      - name: Push Images
        run: |
          # Staging Image
          docker tag ${{ steps.image-id.outputs.IMAGE_ID }} cx-harbor.btech.id/calc/test-app:${{ steps.get-version.outputs.VERSION }}-rc
          docker push cx-harbor.btech.id/calc/test-app:${{ steps.get-version.outputs.VERSION }}-rc
          # Production Image
          docker tag cx-harbor.btech.id/calc/test-app:${{ steps.get-version.outputs.VERSION }}-rc cx-harbor.btech.id/calc/test-app:${{ steps.get-version.outputs.VERSION }}
          docker push cx-harbor.btech.id/calc/test-app:${{ steps.get-version.outputs.VERSION }}

      - name: Update Manifest Yaml
        run: |
          cd infra/staging
          yq e -i '.spec.template.spec.containers[0].image="cx-harbor.btech.id/calc/test-app:${{ steps.get-version.outputs.VERSION }}-rc"' calc-deployment.yml
          cat calc-deployment.yml

      - name: Push Change Back to Github
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: infra/staging/calc-deployment.yml
          destination_repo: rjhaikal/github-argo
          destination_branch: staging
          destination_folder: infra/staging
          user_email: majidqoba52@gmail.com
          user_name: rjhaikal
          commit_message: update image version ${{ steps.get_version.outputs.VERSION }} in yml file
  
  image-scanning:
    name: Image Scanning
    needs: build-image
    runs-on: self-hosted
    steps:
      - name: get version
        id: get-version
        run: |
          echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'cx-harbor.btech.id/calc/test-app:${{ steps.get-version.outputs.VERSION }}-rc'
          format: 'table'
          exit-code: '0'
          severity: 'MEDIUM,HIGH,CRITICAL'

  deploy-staging:
    name: Deploy Staging
    needs: [build-image, image-scanning]
    runs-on: self-hosted
    environment:
      name: Staging
    steps:
      - name: ArgoCD Deploy to Staging
        run: |
          echo ${{ secrets.HARBOR_PASSWORD }} | docker login ${{ secrets.HARBOR_URL }} -u ${{ secrets.HARBOR_USERNAME }} --password-stdin
          argocd login --insecure  ${{ secrets.ARGOCD_SERVER }} --username  ${{ secrets.ARGOCD_CREDS_USR }} --password  ${{ secrets.ARGOCD_CREDS_PSW}}
          argocd app create test-app-staging --project default --repo https://github.com/rjhaikal/github-argo.git --revision staging --path ./infra/staging --dest-namespace calc-stg --dest-server https://kubernetes.default.svc --upsert
          argocd --grpc-web app sync test-app-staging --force 
          argocd --grpc-web app wait test-app-staging --timeout 600

  deploy-production:
    name: Deploy Production
    needs: [build-image, image-scanning, deploy-staging]
    runs-on: self-hosted
    environment:
      name: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: get version
        id: get-version
        run: |
          echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Update Manifest Yaml
        run: |
          cd infra/production
          yq e -i '.spec.template.spec.containers[0].image="cx-harbor.btech.id/calc/test-app:${{ steps.get-version.outputs.VERSION }}"' calc-deployment.yml
          cat calc-deployment.yml

      - name: Push Change Back to Github
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: infra/production/calc-deployment.yml
          destination_repo: rjhaikal/github-argo
          destination_branch: production
          destination_folder: infra/production
          user_email: majidqoba52@gmail.com
          user_name: rjhaikal
          commit_message: update image version ${{ steps.get_version.outputs.VERSION }} in yml file

      - name: ArgoCD Deploy to Production
        run: |
          echo ${{ secrets.HARBOR_PASSWORD }} | docker login ${{ secrets.HARBOR_URL }} -u ${{ secrets.HARBOR_USERNAME }} --password-stdin
          argocd login --insecure  ${{ secrets.ARGOCD_SERVER }} --username  ${{ secrets.ARGOCD_CREDS_USR }} --password  ${{ secrets.ARGOCD_CREDS_PSW}}
          argocd app create test-app-prod --project default --repo https://github.com/rjhaikal/github-argo.git --revision production --path ./infra/production --dest-namespace calc --dest-server https://kubernetes.default.svc --upsert
          argocd --grpc-web app sync test-app-prod --force 
          argocd --grpc-web app wait test-app-prod --timeout 600
